SSEG    SEGMENT
STACK   DW      50 DUP (0)
SSEG    ENDS
CSEG    SEGMENT
		ASSUME  CS:CSEG, ASSUME  SS:SSEG
START:  
	MOV AX, 4H;
	MOV BX, AX;
	MOV AX, 5H;
	ADD BX, AX;
	MOV BX, BX;
	MOV AX, 6H;
	SUB BX, AX;
	MOV     AH, 4CH
	INT     21H
CSEG    ENDS
		END     START
